roi_size: [64,64,64]        # 3D patch-size
input_channels: 1           # input channels of 3D CNN
output_dim: 3               # number of labels including background 
base_features: 32           # base features of feature-pyramid in the encoder/decoder (after each layer it will be doubled)
projected_dim: 128          # projection head dimension
batch_size: 32              # batch size
learning_rate: 0.00001      # learning rate
num_epochs: 500            # number of epochs

spacing: [1.5,1.5,1.5]      # change the spacing to new values
min_intensity: -200         # min HU for intensity preprocessing
max_intensity: 400          # max HU for intensity preprocessing

images_dir: "/home/Downloads/Task07_Pancreas/Task07_Pancreas/imagesTr"  # Images directory
data_root_dir: "/home/Downloads/Task07_Pancreas/Task07_Pancreas"        # Root directory contains images and labels directories 

checkpoint_dir_cl: "./ModelCheckpoints/CL_models_pancreas"    # contrastive learning models checkpoints save dir
checkpoint_dir_seg: "./ModelCheckpoints/Seg_models_pancreas"  # segmentation models checkpoints save dir
